### ISSUE TITLE
python 3.9

### ISSUE THREAD

**Issue by zerapat** [njvack/bids-json-writer#12]
markdown-to-json does not work with python 3.9. I applied a fix to CommonMark.py but are not allowed to push it

**Comment by njvack** [comment]
I'll totally accept a PR, it's not like I've actually been taking care of this project.

**Comment by bobromeo** [comment]
I think i did the same fix using an install og commonmark --> common.py  but after that you get 
AttributeError: 'list' object has no attribute 'items'

**Comment by plt3** [comment]
Did you just change line 19 of CommonMark.py to `HTMLunescape = html.unescape`? I did that and it seemed to work for me. Not sure if this brings up bugs in other cases but if not I could make a PR with just that change.

**Comment by njvack** [comment]
goodness, I don't know 😬

Again, I'll absolutely merge a PR

The Right Thing to do is use a more modern markdown library (https://github.com/executablebooks/markdown-it-py maybe) that doesn't produce such a weird syntax tree, dropping python 2 is also well past due

also why do people have this project starred, this is a gross implementation of an objectively silly concept

**Comment by plt3** [comment]
Cool, sorry for taking so long but I made a quick PR for this. It's a pretty trivial change but would be nice to have it updated in the version of this package that's on pypi!

**Comment by njvack** [comment]
Okay! I merged this PR and pushed a new version to pypi
